theme: jekyll-theme-minimal
title: "InstaTools by Micha Birklbauer"
description: "Project Website for InstaTools - A Python Package for using Instagram"
logo: https://raw.githubusercontent.com/t0xic-m/t0xic-m.github.io/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/t0xic-m/instatools/archive/master.zip
  tar_url: https://github.com/t0xic-m/instatools/archive/master.tar.gz
