theme: jekyll-theme-minimal
title: "InstaTools by Micha Birklbauer"
description: "Project Website for InstaTools - A Python Package for using Instagram"
logo: https://raw.githubusercontent.com/michabirklbauer/projects/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/michabirklbauer/instatools/archive/master.zip
  tar_url: https://github.com/michabirklbauer/instatools/archive/master.tar.gz
